# 06a · Audit – fact_lva_stats

**Zweck**  
Blitz-Qualitäts-Check nach jedem Load:
- zählt NULL-Werte in allen FK- & Kennzahlspalten  
- zählt FK-Referenzen auf `UNKNOWN` (= 0)  
- zeigt Zeilenanzahl pro Flag-Kombi (LVA/Wiedereinstieg)

**Ergebnis**  
Ein transponierter Ein-Zeilen-DataFrame und optional CSV-Export.


Audit notebook: rein strukturell, läuft automatisiert nach jedem ETL-Run.

In [1]:
# %% ───────── Setup ─────────
import pandas as pd
from sqlalchemy import create_engine, text

ENG = create_engine(
    "mysql+pymysql://root:voc_root@localhost:3306/vocdata",
    future=True, echo=False)

# FK- und Kennzahlspalten
FK_COLS  = [
    "abschlussniveau_id", "lernform_id", "geschlecht_id", "mig_status_id",
    "anschlussart_id", "qv_status_id", "lva_zeitpunkt_id",
    "wiedereinst_dauer_id", "isced_id", "beruf_id"
]
NUM_COLS = [
    "anzahl_lernende_lva", "anzahl_lernende_wiedereinstieg",
    "anzahl_lernende", "anzahl_lehrvertraege_lva", "anzahl_lehrvertraege"
]

# %% ───────── Audit-Funktion ─────────
def audit_fact(table: str, fk_cols: list, num_cols: list) -> pd.DataFrame:
    sel = ["COUNT(*) AS total_rows"]
    sel += [f"SUM({c} IS NULL) AS null_{c}" for c in fk_cols + num_cols]
    sel += [f"SUM({c}=0)        AS fk0_{c}"  for c in fk_cols]
    sql = f"SELECT {', '.join(sel)} FROM {table};"
    return pd.read_sql(text(sql), ENG).T.rename(columns={0: table})

# %% ───────── Ergebnis ─────────
display(audit_fact("fact_lva_stats", FK_COLS, NUM_COLS))

                                     fact_lva_stats
total_rows                                   1081.0
null_abschlussniveau_id                         0.0
null_lernform_id                                0.0
null_geschlecht_id                              0.0
null_mig_status_id                              0.0
null_anschlussart_id                            0.0
null_qv_status_id                               0.0
null_lva_zeitpunkt_id                           0.0
null_wiedereinst_dauer_id                       0.0
null_isced_id                                   0.0
null_beruf_id                                   0.0
null_anzahl_lernende_lva                      649.0
null_anzahl_lernende_wiedereinstieg           894.0
null_anzahl_lernende                          501.0
null_anzahl_lehrvertraege_lva                1057.0
null_anzahl_lehrvertraege                    1081.0
fk0_abschlussniveau_id                          0.0
fk0_lernform_id                              1075.0
fk0_geschlecht_id                            1042.0
fk0_mig_status_id                            1021.0
fk0_anschlussart_id                          1057.0
fk0_qv_status_id                              717.0
fk0_lva_zeitpunkt_id                         1069.0
fk0_wiedereinst_dauer_id                     1081.0
fk0_isced_id                                 1081.0
fk0_beruf_id                                  439.0