In [3]:
import pandas as pd
from pathlib import Path

excel_path = Path(r"C:\Users\claud\iCloudDrive\Dokumente\02_CLI\Studium\ZHAW\Masterarbeit\vocdata\data\bfs_data_abschlussquote.xlsx")
xls = pd.ExcelFile(excel_path)

print("Gefundene Sheets:", xls.sheet_names, "\n")

for sheet in xls.sheet_names:
    if sheet.endswith("_Data"):
        df = pd.read_excel(xls, sheet_name=sheet, nrows=10)
        print(f"--- {sheet} ---")
        display(df)

Gefundene Sheets: ['T1_SekII_1st_25_Merkm_Data', 'T1_SekII_1st_25_Merkm_Dict', 'T2_SekII_1st_25_Kant_Data', 'T2_SekII_1st_25_Kant_Dict.', 'T3_Matura_Merkm_data', 'T3_Matura_Merk_dict', 'T4_Matura_Kant_data', 'T4_Matura_Kant_dict']

--- T1_SekII_1st_25_Merkm_Data ---

,jahr,merkmal,kategorie,total_anz_25J,total_anz_sekII_erstabschluss_25J,Lehre_anz_sekII_erstabschluss_25J,allg_bildg_anz_sekII_erstabschluss_25J,total_%_sekII_erstabschluss_25J,Lehre_%_sekII_erstabschluss_25J,allg_bildg_%_sekII_erstabschluss_25J
0,2022,Total,NaN,80423,72437,48819,23618,90.100,60.700,29.400
1,2022,Geschlecht,Männer,41437,36684,27375,9309,88.529,66.064,22.465
2,2022,Geschlecht,Frauen,39018,35753,21449,14304,91.632,54.972,36.660
3,2022,Migrationskategorie,in der Schweiz geborene Schweizer/innen,60557,55798,37187,18611,92.142,61.409,30.733
4,2022,Migrationskategorie,in der Schweiz geborene Ausländer/innen,7745,6587,5265,1322,85.049,67.984,17.065
5,2022,Migrationskategorie,im Ausland geborene Schweizer/innen,2771,2354,1262,1092,84.955,45.558,39.397
6,2022,Migrationskategorie,im Ausland geborene Ausländer/innen,8921,7612,5035,2577,85.325,56.442,28.883
7,2022,Sprachregion,deutschsprachige und rätoromanische Schweiz,55411,50709,37533,13176,91.515,67.736,23.779
8,2022,Sprachregion,französischsprachige Schweiz,21621,18670,9301,9369,86.352,43.017,43.335
9,2022,Sprachregion,italienischsprachige Schweiz,3383,3058,1982,1077,90.402,58.581,31.821

--- T2_SekII_1st_25_Kant_Data ---

,jahr,merkmal,kategorie,total_anz_25J,total_anz_sekII_erstabschluss_25J,Lehre_anz_sekII_erstabschluss_25J,allg_bildg_anz_sekII_erstabschluss_25J,total_%_sekII_erstabschluss_25J,Lehre_%_sekII_erstabschluss_25J,allg_bildg_%_sekII_erstabschluss_25J
0,2022,Total,CH,80423,72437,48819,23618,0.90,0.61,0.29
1,2022,Wohnkanton,ZH,13265,12115,8812,3303,0.91,0.66,0.25
2,2022,Wohnkanton,BE,9307,8555,6439,2116,0.92,0.69,0.23
3,2022,Wohnkanton,LU,3865,3519,2703,816,0.91,0.70,0.21
4,2022,Wohnkanton,UR,368,351,289,62,0.95,0.79,0.17
5,2022,Wohnkanton,SZ,1488,1375,1040,335,0.92,0.70,0.22
6,2022,Wohnkanton,OW,362,343,270,73,0.95,0.74,0.20
7,2022,Wohnkanton,NW,387,349,267,82,0.90,0.69,0.21
8,2022,Wohnkanton,GL,373,349,286,63,0.94,0.77,0.17
9,2022,Wohnkanton,ZG,1175,1078,686,392,0.92,0.58,0.33